### ISSUE TITLE
Debian: type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception 

### ISSUE THREAD

**Issue by lytico** [dotdevelop/libgit2sharp#2]
See 
https://github.com/libgit2/libgit2sharp/issues/1533#issuecomment-661287726
and
https://github.com/dotdevelop/dotdevelop/issues/52#issuecomment-771183443

the branch to fix it is this: https://github.com/dotdevelop/libgit2sharp/tree/dd/issues/2

the git hash for libgit is 6777db8e8343014d57c41b335e0c60af44d4e9f2 ->

**Comment by lytico** [comment]
so, according to @Molytho , the problem is in the mismatch from

https://github.com/dotdevelop/libgit2/blob/6777db8e8343014d57c41b335e0c60af44d4e9f2/include/git2/status.h#L170-L197

to

https://github.com/dotdevelop/libgit2sharp/blob/3a544afbe551ae4ae6ff4b4f732f1341d3b5b966/LibGit2Sharp/Core/GitStatusOptions.cs#L6-L20

calling https://github.com/dotdevelop/libgit2sharp/blob/3a544afbe551ae4ae6ff4b4f732f1341d3b5b966/LibGit2Sharp/RepositoryStatus.cs#L61

**Comment by Molytho** [comment]
I started testing and I think I found a solution/workaround. I don't know how to set the project up properly to use a self build nuget for libgit2-sharp so I changed it to a project reference so this might not be 100% accurate.

First I compiled it with a clean clone of this repo. It didn't work.
Then I added the line
`public unsafe void* Baseline = (void*)0;`
to the end of the GitStatusOptions class. After that it worked fine.

**Comment by hwthomas** [comment]
It's surprising that this mis-match hasn't caused problems long before now!  It seems to be in the current `master` and latest release (`maint/v0.26`) branches of `github/libgit2/libgit2sharp`, and not just the `mono/dotdevelop` forks.  
Well tracked down @Molytho!

**Comment by lytico** [comment]
maybe it has to do with a more sever (and saver) memory access control in recent versions of mono?

and, yes, @Molytho did a great job, and he should upstream that error in the github/libgit2/libgit2sharp - repo.

**Comment by hwthomas** [comment]
Could the LibGit2Sharp.NativeBinaries be updated with this change, together with the dotdevelop build, please (even though the 'no TLS stream' issue is still outstanding)?  Thanks.

**Comment by lytico** [comment]
Yes. Done..

**Comment by Molytho** [comment]
The fix got merged to upstream:
https://github.com/libgit2/libgit2sharp/commit/b78b2900dfe3dc835e0e79f6e542672826bdbc9a

**Comment by hwthomas** [comment]
That's great. It seems that this has now fixed a problem that upstream libgit2 were having with dotnet runtime 5.0.7, so many thanks all round  @Molytho !
